package com.kafune.appy2k.effects

data class Preset(
    val id: String,
    val name: String,
    val params: EffectParams,
)

/**
 * Cada preset é só um conjunto de parâmetros do über-shader + pipeline
 * de export. Pra criar um novo, copie um existente e ajuste.
 */
val PRESETS: List<Preset> = listOf(
    Preset(
        id = "original",
        name = "Original",
        params = EffectParams.NEUTRAL,
    ),
    Preset(
        id = "digicam03",
        name = "Digicam ’03",
        params = EffectParams(
            softness = 0.55f,
            ca = 0.35f,
            bloom = 0.35f,
            crush = 0.35f,
            saturation = 1.18f,
            colorCast = 0.5f,
            grain = 0.3f,
            vignette = 0.2f,
            blockiness = 0.25f,
            lut = "sony_ccd",
            jpegQuality = 55,
            jpegPasses = 1,
            outputLongEdge = 1600,
            timestamp = true,
            timestampYearOffset = -23, // sua foto "de 2003"
        ),
    ),
    Preset(
        id = "flash",
        name = "Flash Estourado",
        params = EffectParams(
            softness = 0.4f,
            ca = 0.45f,
            bloom = 1.1f,
            crush = 0.6f,
            saturation = 1.1f,
            colorCast = 0.55f,
            grain = 0.45f,
            vignette = 0.55f,
            blockiness = 0.2f,
            lut = "canon_ixus",
            jpegQuality = 60,
            outputLongEdge = 1600,
            timestamp = true,
            timestampYearOffset = -22,
        ),
    ),
    Preset(
        id = "shoegaze",
        name = "Shoegaze",
        params = EffectParams(
            softness = 0.8f,
            ca = 0.3f,
            bloom = 0.7f,
            ghost = 0.75f,
            ghostAngle = 20f,
            fade = 0.45f,
            saturation = 0.72f,
            colorCast = 0.4f,
            grain = 0.7f,
            vignette = 0.5f,
            lut = "fuji_finepix",
            lutMix = 0.7f,
            jpegQuality = 70,
            outputLongEdge = 1800,
        ),
    ),
    Preset(
        id = "orkut",
        name = "Orkut",
        params = EffectParams(
            softness = 0.5f,
            ca = 0.2f,
            crush = 0.3f,
            saturation = 1.3f,
            colorCast = 0.35f,
            grain = 0.2f,
            poster = 0.65f,
            blockiness = 0.6f,
            lut = "kodak_easyshare",
            jpegQuality = 28,
            jpegPasses = 2,
            outputLongEdge = 1280,
            timestamp = true,
            timestampYearOffset = -19, // era Orkut
        ),
    ),
    Preset(
        id = "bleach",
        name = "Bleach Bypass",
        params = EffectParams(
            softness = 0.3f,
            ca = 0.15f,
            bloom = 0.45f,
            crush = 0.7f,
            fade = 0.15f,
            saturation = 0.35f,
            colorCast = 0.25f,
            grain = 0.55f,
            vignette = 0.45f,
            jpegQuality = 75,
            outputLongEdge = 2048,
        ),
    ),
    Preset(
        id = "emo",
        name = "Emo Night",
        params = EffectParams(
            softness = 0.45f,
            ca = 0.5f,
            bloom = 0.8f,
            ghost = 0.25f,
            crush = 0.75f,
            fade = 0.2f,
            saturation = 0.9f,
            colorCast = 0.7f,
            grain = 0.6f,
            vignette = 0.7f,
            blockiness = 0.3f,
            lut = "canon_ixus",
            lutMix = 0.8f,
            jpegQuality = 45,
            outputLongEdge = 1600,
            timestamp = true,
            timestampYearOffset = -18, // fundo do poço emo: 2008
        ),
    ),
)
